builds:
  # You can have multiple builds defined as a yaml list
  - # Custom ldflags.
    #
    # Default: '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser'
    # Templates: allowed
    ldflags:
      - -s -w -X conf.version={{.Version}} -X conf.commit={{.Commit}} -X conf.date={{.Date}} -X conf.goVer={{.Env.GOVERSION}}
    # Custom environment variables to be set during the builds.
    # Invalid environment variables will be ignored.
    #
    # Default: os.Environ() ++ env config section
    # Templates: allowed (since v1.14)
    env:
      - CGO_ENABLED=0
    # GOOS list to build for.
    # For more info refer to: https://golang.org/doc/install/source#environment
    #
    # Default: [ 'darwin', 'linux', 'windows' ]
    goos: ['darwin', 'linux', 'windows']
    # GOARCH to build for.
    # For more info refer to: https://golang.org/doc/install/source#environment
    #
    # Default: [ '386', 'amd64', 'arm64' ]
    goarch: [ '386', 'amd64', 'arm64' ]
    # List of combinations of GOOS + GOARCH + GOARM to ignore.
    ignore:
      - goos: 'darwin'
        goarch: 'amd64'

changelog:
  sort: asc
  filters:
    exclude:
      - "^doc:"

upx:
  - enabled: true
    goos: ['linux', 'windows', 'darwin']
    goarch: ['386']
    # Compress argument.
    # Valid options are from '1' (faster) to '9' (better), and 'best'.
    compress: best
    # Whether to try LZMA (slower).
    lzma: true
    # Whether to try all methods and filters (slow).
    brute: true
  - enabled: true
    goos: ['linux', 'windows']
    goarch: ['amd64']
    compress: best
    lzma: true
    brute: true
  - enabled: true
    goos: ['linux']
    goarch: ['arm64']
    compress: best
    lzma: true
    brute: true

archives:
  - # Archive format.
    #
    # If format is `binary`, no archives are created and the binaries are instead
    # uploaded directly.
    #
    # Valid options are `tar.gz`, `tgz`, `tar.xz`, `txz`, tar`, `gz`, `zip`, and `binary`.
    # Default: 'tar.gz'
    format: tar.gz
    format_overrides:
      - # Which GOOS to override the format for.
        goos: windows

        # The format to use for the given GOOS.
        #
        # Valid options are `tar.gz`, `tgz`, `tar.xz`, `txz`, tar`, `gz`, `zip`, `binary`, and `none`.
        format: zip