version: 2
before:
  hooks:
    - go mod tidy
dist: build
builds:
  # You can have multiple builds defined as a yaml list
  - id: combined
    binary: slider_{{ .Os }}_{{ .Arch }}
    main: .
    flags:
      - -trimpath
    # Custom ldflags.
    #
    # Default: '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser'
    # Templates: allowed
    ldflags:
      - -s -w
      - -X slider/pkg/conf.Version={{.Version}}
      - -X slider/pkg/conf.binOS={{.Os}}
      - -X slider/pkg/conf.binArch={{.Arch}}
      - -X slider/pkg/conf.commit={{.Commit}}
      - -X slider/pkg/conf.date={{.Date}}
      - -X slider/pkg/conf.goVer={{.Env.GOVERSION}}
    # Custom environment variables to be set during the builds.
    # Invalid environment variables will be ignored.
    #
    # Default: os.Environ() ++ env config section
    # Templates: allowed (since v1.14)
    env:
      - CGO_ENABLED=0
      - GOVERSION={{ .Env.GOVERSION }}
    # GOOS list to build for.
    # For more info refer to: https://golang.org/doc/install/source#environment
    #
    # Default: [ 'darwin', 'linux', 'windows' ]
    goos: ['darwin', 'linux', 'windows']
    # GOARCH to build for.
    # For more info refer to: https://golang.org/doc/install/source#environment
    #
    # Default: [ '386', 'amd64', 'arm64' ]
    goarch: [ '386', 'amd64', 'arm64' ]
    # List of combinations of GOOS + GOARCH + GOARM to ignore.
    ignore:
      - goos: 'darwin'
        goarch: '386'
    # By default, GoReleaser will create your binaries inside
    # `dist/${BuildID}_${BuildTarget}`, which is a unique directory per build
    # target in the matrix.
    # You can set subdirs within that directory using the `binary` property.
    #
    # However, if for some reason you don't want that unique directory to be
    # created, you can set this property.
    # If you do, you are responsible for keeping different builds from
    # overriding each other.
    no_unique_dist_dir: true
    # Overrides allows to override some fields for specific targets.
    # This can be specially useful when using CGO.
    # Note: it'll only match if the full target matches.
    #
    # Since: v1.5
    overrides:
      - goos: darwin
        goarch: arm64
        goamd64: v1
changelog:
  sort: asc
  filters:
    exclude:
      - "^doc:"
      - "^action:"

upx:
  - enabled: true
    goos: ['linux', 'windows']
    goarch: ['386']
    # Compress argument.
    # Valid options are from '1' (faster) to '9' (better), and 'best'.
    compress: best
    # Whether to try LZMA (slower).
    lzma: true
    # Whether to try all methods and filters (slow).
    brute: true
  - enabled: true
    goos: ['linux', 'windows', 'darwin']
    goarch: ['amd64']
    compress: best
    lzma: true
    brute: true
  - enabled: true
    goos: ['linux']
    goarch: ['arm64']
    compress: best
    lzma: true
    brute: true

archives:
  - # Archive format.
    #
    # If format is `binary`, no archives are created and the binaries are instead
    # uploaded directly.
    #
    # Valid options are `tar.gz`, `tgz`, `tar.xz`, `txz`, tar`, `gz`, `zip`, and `binary`.
    # Default: 'tar.gz'
    formats: ['tar.gz']
    format_overrides:
      - # Which GOOS to override the format for.
        goos: windows

        # The format to use for the given GOOS.
        #
        # Valid options are `tar.gz`, `tgz`, `tar.xz`, `txz`, tar`, `gz`, `zip`, `binary`, and `none`.
        formats: ['zip']